# Generated by Django 3.0.8 on 2020-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gdrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField(max_length=600)),
                ('thumbnail', models.ImageField(upload_to='streamd/thumbnail')),
                ('gdrive_link', models.CharField(max_length=200)),
            ],
        ),
    ]
